### ISSUE TITLE
Add payload release mode in plane

### ISSUE THREAD

**Issue by shovan777** [prokuranepal/ardupilot#1]
## Feature request

**Is your feature request related to a problem? Please describe.**
_A Payload dropped with do_set_servo() simply opens the servo at the given location so, we have no control over where the payload drops. The problem is much more grave in fixed wing UAVs as payload is dropped from a moving aircraft making it accelerate and drop in uncontrolled manner.

**Describe the solution you'd like**
_A Make a mode called payload_release which will plan the location to release the payload and move the aircraft in such a way that payload is dropped to the targeted location precisely.
**Describe alternatives you've considered**
_A Other solution may involve beacon system or the whole flight planning and release point selection may be done at a higher level of abstraction in the ground control station.
**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ x ] Plane
[  ] Rover
[  ] Submarine

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by aabs7** [comment]
The code should be written in a standard way and in the right place for adding features in ArduPlane.

**Comment by shovan777** [comment]
The mode add feature diverges in Plane compared to copter in following ways:
1. land, loiter, like mini modes are completely separate from auto mode in plane
2. there are only start and verify commands and no run command
3. the start and verify command live in command_logic.cpp instead of mode_auto.cpp

**Comment by aabs7** [comment]
Although the method of adding flight mode varies in ArduPlane compared to ArduCopter, a standard way must be researched and followed in the entire process of adding features. I will work on that and follow up.

**Comment by aabs7** [comment]
Commit of a1324afb659266098e1ca2b82fa9bbdb736d5aed above addresses following changes:
- Commented //added & end with //add finish above and below lines of code that are added
- In [parameters.cpp](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/Parameters.cpp), 24:PAYLOADRELEASE  added under FLTMODE(1~6). This is the best practice. 
- In [plane.h](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/Plane.h) mode_payloadrelease object is returned instead of mode_auto object

**Comment by aabs7** [comment]
Commit of cb8275e above addresses the following changes:
- The bool `is_payload_released` is removed from [plane.h](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/Plane.h) auto_state structure, because this boolean is not auto mode mission state, and is added to `ModePayloadRelease` flight mode state inside [mode.h](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/mode.h).
- Special condition checking of `MAV_CMD_NAV_PAYLOAD_RELEASE` inside [mode_auto.cpp](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/mode_auto.cpp) is removed because this command can be called and implemented in `start_command` and `verify_command` functions inside [command_logic.cpp](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/commands_logic.cpp).

#### Further addition of features:
Addition of features should be done in the `update` function inside `mode_payloadrelease.cpp` and `verify_payload_release` & `do_payload_release` functions inside [command_logic.cpp](https://github.com/aabs7/ardupilot/blob/master/ArduPlane/commands_logic.cpp).

**Comment by shovan777** [comment]
#2 while implementing the wind based payload drop calculations the faulty wind estimate was observed.

**Comment by aabs7** [comment]
### Up to now 
- The plane calculates the release point taking into account wind velocity for the payload to reach target drop point. The calculation of the release point can be found [here](https://github.com/prokuranepal/UAV-Payload-Drop).
- Intermediate point is calculated from release point parallel to direction plane is flying.
- The plane loiters around center perpendicular from the line of intermediate point and the release point with distance R from the intermediate point and radius R. 
- The plane leaves from loitering making tangent towards release point.   
![this](https://user-images.githubusercontent.com/25321415/84850762-3f225480-b078-11ea-8dad-a2fa7ca27ab9.png)  
In the figure above, waypoint 9 is the target drop point. 

### To do
- Add servo functionality when reached release point.
- code refactoring.

**Comment by aabs7** [comment]
The current version supports a single release point calculation.  For continuous release point updates, the code has to be extended for the plane to reach changing waypoint.
